# Do not use this for production.
version: "3"

services:
  zetacore0:
    container_name: zetacore0
    env_file:
      - .env
    image: zetacore:latest
    environment:
      - NODE_NUMBER=0
    volumes:
      - ./storage/node0/zetaclient:/root/.zetaclient
      - ./storage/node0/zetacore:/root/.zetacore
      - ./storage/node0/tss:/root/.tss/
      - ./storage/node0/tssnew/:/root/.tssnew/
      - ../../build:/scripts
      - ./config/:/zetashared/

    ports:
        - "${REST_ENDPOINT}:1317" # REST_ENDPOINT
        - "${gRPC_PORT}:9090" # gRPC_PORT
        - "${RPC_PORT}:26657" # RPC_PORT
    networks:
      localnet:
        ipv4_address: 172.24.0.200
    command: -c "/scripts/zetacored-start.sh 0"
  zetacore1:
    container_name: zetacore1
    env_file:
      - .env
    image: zetacore:latest
    environment:
      - NODE_NUMBER=1
    volumes:
      - ./storage/node1/zetaclient:/root/.zetaclient
      - ./storage/node1/zetacore:/root/.zetacore
      - ./storage/node1/tss:/root/.tss/
      - ./storage/node1/tssnew/:/root/.tssnew/
      - ../../build:/scripts
      - ./config/:/zetashared/
    networks:
      localnet:
        ipv4_address: 172.24.0.201
    command: -c "/scripts/zetacored-start.sh 1 zetacore0"

  zetaclient0:
    container_name: zetaclient0
    restart: unless-stopped
    env_file:
      - .env
    image: zetacore:latest
    # depends_on:
    #   - zetacore0
    environment:
      - NODE_NUMBER=0
      - BOOTNODE_IP=zetacore0
      - CHAIN_IP=zetacore0
      - ROPSTEN_MPI_ADDRESS=$ETH_CONNECTOR_ADDRESS
      - GOERLI_MPI_ADDRESS=$ETH_CONNECTOR_ADDRESS
      - BSCTESTNET_MPI_ADDRESS=$BSC_CONNECTOR_ADDRESS
      - MUMBAI_MPI_ADDRESS=$POLYGON_CONNECTOR_ADDRESS
      - GOERLI_ENDPOINT=$ETH_ENDPOINT
      - ROPSTEN_ENDPOINT=$ETH_ENDPOINT
      - BSCTESTNET_ENDPOINT=$BSC_ENDPOINT
      - MUMBAI_ENDPOINT=$POLYGON_ENDPOINT
      
    volumes:
      - ./storage/node0/zetaclient:/root/.zetaclient
      - ./storage/node0/zetacore:/root/.zetacore
      - ./storage/node0/tss:/root/.tss
      - ./storage/node0/tssnew/:/root/.tssnew/
      - ../../build:/scripts
      - ./config/:/zetashared/
    ports:
      - 8123:8123
    networks:
      localnet:
        ipv4_address: 172.24.0.220
    command: -c "/scripts/zetaclient-start.sh 0"
  zetaclient1:
    container_name: zetaclient1
    restart: unless-stopped
    env_file:
      - .env
    image: zetacore:latest
    # depends_on:
    #   - zetacore1
    environment:
      - NODE_NUMBER=1
      - BOOTNODE_IP=zetacore1
      - CHAIN_IP=zetacore1
      - ROPSTEN_MPI_ADDRESS=$ETH_CONNECTOR_ADDRESS
      - GOERLI_MPI_ADDRESS=$ETH_CONNECTOR_ADDRESS
      - BSCTESTNET_MPI_ADDRESS=$BSC_CONNECTOR_ADDRESS
      - MUMBAI_MPI_ADDRESS=$POLYGON_CONNECTOR_ADDRESS

      - GOERLI_ENDPOINT=$ETH_ENDPOINT
      - ROPSTEN_ENDPOINT=$ETH_ENDPOINT
      - BSCTESTNET_ENDPOINT=$BSC_ENDPOINT
      - MUMBAI_ENDPOINT=$POLYGON_ENDPOINT
    volumes:
      - ./storage/node1/zetaclient:/root/.zetaclient
      - ./storage/node1/zetacore:/root/.zetacore
      - ./storage/node1/tss:/root/.tss
      - ./storage/node1/tssnew/:/root/.tssnew/
      - ../../build:/scripts
      - ./config/:/zetashared/
    networks:
      localnet:
        ipv4_address: 172.24.0.221
    command: -c "/scripts/zetaclient-start.sh 1 zetaclient0"
    
networks:
  localnet: 
    external: true
    name: localnet
