version: "3"

services:
  bsc: # This is the bootstrap node
    image: bsc-geth:docker-local
    platform: linux/amd64
    env_file: .env
    ports:
      - ${RPC_PORT}:8545
    environment:
      NODE_ID: bsc
    volumes:
      - ./storage/:/root/.ethereum
      - ./config:/config
    networks:
      - localnet
    command: > 
      geth --config /config/config.toml
      --datadir /root/.ethereum
      --nousb
      --http
      --http.addr="0.0.0.0"
      --rpcvhosts=*
      --http.api="eth,web3,net,admin,personal"
      --http.corsdomain="*"
      --networkid=${NETWORK_ID}
      --dev
      --dev.period=5
      --unlock=0 --password=/dev/null
      --nodiscover
      --mine
      --pprof.addr=0.0.0.0 
      --metrics 
      --rpc.allow-unprotected-txs 
      --txlookuplimit=15768000 
      --ethstats bsc:bscpwd@netstats:3000 


  netstats:
    build: ./bsc-docker/netstats/
    ports:
      - 3010:3000
    environment:
      WS_SECRET: bscpwd
    restart: always
    networks:
      - localnet
    
networks:
  localnet: 
    external: true
    name: localnet
