# Do not use this for production.
version: "3"

services:
  zetacore0:
    container_name: zetacore0
    env_file:
      - .env
    image: zetacore:latest
    environment:
      - NODE_NUMBER=0
    volumes:
      - ./storage/node0/zetaclient:/root/.zetaclient
      - ./storage/node0/zetacore:/root/.zetacore
      - ./storage/node0/tss:/root/.tss/
      - ./storage/node0/tssnew/:/root/.tssnew/
      - ../../../build:/scripts
      - ./config/:/zetashared/

    ports:
        - "${REST_ENDPOINT}:1317" # REST_ENDPOINT
        - "${gRPC_PORT}:9090" # gRPC_PORT
        - "${RPC_PORT}:26657" # RPC_PORT
    networks:
      localnet:
        ipv4_address: 172.24.0.200
    command: -c "/scripts/create-genesis-files.sh 0 1"
    
  zetacore1:
    container_name: zetacore1
    env_file:
      - .env
    image: zetacore:latest
    environment:
      - NODE_NUMBER=1
    volumes:
      - ./storage/node1/zetaclient:/root/.zetaclient
      - ./storage/node1/zetacore:/root/.zetacore
      - ./storage/node1/tss:/root/.tss/
      - ./storage/node1/tssnew/:/root/.tssnew/
      - ../../../build:/scripts
      - ./config/:/zetashared/
    networks:
      localnet:
        ipv4_address: 172.24.0.201
    command: -c "/scripts/create-genesis-files.sh 1 1"


networks:
  localnet: 
    external: true
    name: localnet