# Do not use this for production.
version: "3"

services:
  bor:
    container_name: bor
    env_file:
      - .env
    image: bor
    # build: ./bor
    # restart: unless-stopped
    ports:
        - "${RPC_PORT}:8545" # RPC
        # - "30303:30303" # Peers (TCP)
        # - "30303:30303/udp" # Peers (UDP)
    networks:
      - localnet
    command:
        - --datadir=/datadir
        - --networkid=${NETWORK_ID}
        - --http
        - --http.addr=0.0.0.0
        - --http.port=8545
        - --http.api=eth,net,web3,admin,debug,personal
        - --http.corsdomain=*
        - --http.vhosts=*
        - --ws
        - --ws.addr=0.0.0.0
        - --ws.port=8545
        - --ws.api=eth,net,web3,admin,debug,personal
        - --ws.origins=*
        - --mine
        - --miner.gaslimit=200000000
        - --miner.gastarget=20000000
        - --allow-insecure-unlock
        - --nodiscover
        - --unlock=0
        - --password=/tmp/password
        - --dev
        - --dev.period=10
        - --miner.noverify  
        - --fakepow   
        - --bor.withoutheimdall  ## Must replace this with bor.heimdall=http://heimdalld:1317 if you enable the other containers

## Remaining Containers are not needed at this time
## They deploy the full chain connecting a preexisting ETH > to Heimdall > then to Bor 
## Disabled for now

  # rabbitmq:
  #   container_name: rabbitmq
  #   env_file:
  #     - .env
  #   image: rabbitmq:3-alpine
  #   # ports:
  #   #   - "5672:5672" # RabbitMQ
  #   networks:
  #     - localnet
  #   restart: unless-stopped

  # heimdalld:
  #   container_name: heimdalld
  #   env_file:
  #     - .env
  #   image: heimdall:latest
  #   # build: .heimdall
  #   restart: unless-stopped
  #   environment:
  #     - HEIMDALL_ETH_RPC_URL=http://geth-rpc-endpoint:8545
  #     - HEIMDALL_BOR_RPC_URL=http://bor:8545
  #   volumes:
  #     - ./data:/heimdall
  #   # ports:
  #   #   - "26656:26656" # P2P (TCP)
  #   #   - "26657:26657" # RPC (TCP)
  #   networks:
  #     - localnet
  #   depends_on:
  #     - rabbitmq
  #   command:
  #     - start
  #     - --p2p.laddr=tcp://0.0.0.0:26656
  #     - --rpc.laddr=tcp://0.0.0.0:26657
  #     - --http.corsdomain=*
  #     - --eth_rpc_url=
  #     - --bor_rpc_url=

  # heimdallr:
  #   container_name: heimdallr
  #   env_file:
  #     - .env
  #   image: heimdall:latest
  #   build: ./heimdall
  #   restart: unless-stopped
  #   environment:
  #     - HEIMDALL_ETH_RPC_URL=http://geth-rpc-endpoint:8545
  #     - HEIMDALL_BOR_RPC_URL=http://bor:8545
  #   volumes:
  #     - ./data:/heimdall
  #   # ports:
  #     # - "1317:1317" # Heimdall REST API
  #   networks:
  #     - localnet
  #   depends_on:
  #     - heimdalld
  #   command:
  #     - rest-server
  #     - --laddr=tcp://0.0.0.0:1317
  #     - --node=tcp://heimdalld:26657
  #     - --http.corsdomain=*
  #     - --eth_rpc_url=
  #     - --bor_rpc_url=

  # bridge:
  #   container_name: bridge
  #   env_file:
  #     - .env
  #   image: heimdall:latest
  #   build: ./heimdall
  #   restart: unless-stopped
  #   networks:
  #     - localnet
  #   environment:
  #     - HEIMDALL_ETH_RPC_URL=http://geth-rpc-endpoint:8545
  #     - HEIMDALL_AMQP_URL=amqp://guest:guest@rabbitmq:5672
  #     - HEIMDALL_HEIMDALL_REST_SERVER=http://heimdallr:1317
  #     - HEIMDALL_TENDERMINT_RPC_URL=http://heimdalld:26657
  #     - HEIMDALL_BOR_RPC_URL=http://bor:8545
  #   volumes:
  #     - ./data:/heimdall
  #   depends_on:
  #     - heimdalld
  #     - heimdallr
  #     - rabbitmq
  #   command:
  #     - bridge
  #     - start 
  #     - --all
  #     - --http.corsdomain=*
  #     - --eth_rpc_url=
  #     - --bor_rpc_url=

networks:
  localnet: 
    external: true
    name: localnet
