name: Linter
on:
  push:
    tags:
      - v*
      - athens2-*
  pull_request:

env: 
  GOPRIVATE: github.com/zeta-chain/*
  
jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
        
      - name: setup-git-credentials
        uses: de-vri-es/setup-git-credentials@v2.0.8
        with:
          credentials: ${{ secrets.PAT_GITHUB_SERVICE_ACCT }} 
   
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3.3.1
        with:
          version: v1.50
